definitions:
  dto.UserLoginDTO:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
info:
  contact: {}
  description: 接口描述
  title: go-web-api
  version: 1.0 版本
paths:
  /api/v1/public/user/login:
    post:
      consumes:
      - application/json
      description: 用户登录描述
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UserLoginDTO'
      produces:
      - application/json
      responses: {}
      summary: 用户登录
swagger: "2.0"
